# Generated by Django 6.0.1 on 2026-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='king_david.jpg', null=True, upload_to='avatars/'),
        ),
    ]
