# Generated by Django 6.0.1 on 2026-02-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiesapp', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
